#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to:
# 1. install ngix
# 2. Nginx should listen to port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service ngix start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx reload
