#!/usr/bin/env bash
# a bash script that displays numbers from 1-100
# displays fizzbuzz if multiple of 3 and 5
# displays fizz if multiple 3
# displays Buzz if multiple of 5

i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo FizzBuzz
	elif [ $((i % 3)) -eq 0 ]
	then
		echo Fizz
	elif [ $((i % 5)) -eq 0 ]
	then
		echo Buzz
	else
		echo $i
	fi
	((i++))
done
