#!/usr/bin/env bash
# A bash script that that displays Best School 10 times but at the 9th iteration, displays both Best School and Hi on a new line

i=0
while [ $i -lt 10 ]
do
	echo Best School
	if [ "$i" -eq "8" ] ;
	then
		echo Hi
	fi
	((i++))
done
