#!/usr/bin/env bash
# increaments a variable by 1 and prints a string at superstitous numbers

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((i++))
done
