#!/usr/bin/env bash
# a bash script that checks is a fie exists and empty is yes

file="school"
if [ -e $file ]
then
	echo "$file file exists"
	if [ -s $file ]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if [ -f $file ]
	then
		echo "$file file is a regular file"
	fi
else
	echo school file does not exist
fi
